using System;
using UnityEngine;

namespace Unmanaged.LayeredTexture
{
    /// <summary>
    /// Layer that composites a constant color.
    /// </summary>
    [Serializable]
    public sealed class SolidColorLayer : TextureLayerBase
    {
        /// <summary>
        /// Color generated by this layer.
        /// </summary>
        public Color Color = Color.white;

        /// <inheritdoc />
        public override TextureLayerRole Role => TextureLayerRole.Source;

        /// <inheritdoc />
        public override bool SupportsRawPreview => true;

        /// <inheritdoc />
        public override void Process(BakeContext ctx)
        {
            LayerCompute.GetKernelOrThrow(LayerCompute.SolidColorKernel, out var shader, out var kernel);
            LayerCompute.SetCommon(shader, kernel, ctx, Opacity, BlendMode, InputSwizzle, WriteMask);
            shader.SetVector(LayerCompute.ColorId, Color);
            LayerCompute.Dispatch(shader, kernel, ctx);
        }
    }
}
