using System;
using UnityEngine;

namespace Unmanaged.LayeredTexture
{
    /// <summary>
    /// Layer that composites a constant color.
    /// </summary>
    [Serializable]
    public sealed class SolidColorLayer : TextureLayerBase
    {
        /// <summary>
        /// Color generated by this layer.
        /// </summary>
        public Color Color = Color.white;

        /// <inheritdoc />
        public override void Process(BakeContext ctx)
        {
            if (!TryGetShaderKernel(out var shader, out var kernel, out var error))
                throw new InvalidOperationException(error);

            LayerCompute.SetCommon(shader, kernel, ctx, Opacity, BlendMode, InputSwizzle, WriteMask);
            shader.SetVector(LayerCompute.ColorId, Color);
            LayerCompute.Dispatch(shader, kernel, ctx);
        }

        internal static bool TryGetShaderKernel(out ComputeShader shader, out int kernel, out string error) =>
            LayerCompute.TryGetKernel(LayerCompute.SolidColorKernel, out shader, out kernel, out error);
    }
}
