using System;
using UnityEngine;

namespace Unmanaged.LayeredTexture
{
    /// <summary>
    /// Source layer that generates tileable ocean-swell height waves.
    /// </summary>
    [Serializable]
    public sealed class WaterWavesLayer : TextureLayerBase
    {
        /// <summary>
        /// Whether the layer outputs wave height or derived foam.
        /// </summary>
        public WaterWavesOutputMode OutputMode = WaterWavesOutputMode.Height;

        /// <summary>
        /// Deterministic random seed for wave distribution.
        /// </summary>
        public int Seed = 1;

        /// <summary>
        /// Number of directional waves to accumulate.
        /// </summary>
        public int WaveCount = 16;

        /// <summary>
        /// Dominant wave direction in degrees.
        /// </summary>
        public float WindDirection;

        /// <summary>
        /// Direction spread around WindDirection in degrees.
        /// </summary>
        public float DirectionSpread = 35f;

        /// <summary>
        /// Minimum and maximum wave cycles across the UV tile.
        /// </summary>
        public Vector2 CycleRange = new(2f, 14f);

        /// <summary>
        /// Base wave amplitude before normalization.
        /// </summary>
        public float Amplitude = 1f;

        /// <summary>
        /// Amplitude multiplier applied to later waves.
        /// </summary>
        public float AmplitudeFalloff = 0.75f;

        /// <summary>
        /// Bias toward sharper wave crests.
        /// </summary>
        public float Choppiness = 0.25f;

        /// <summary>
        /// Phase offset in normalized cycles.
        /// </summary>
        public float Phase;

        /// <summary>
        /// Height threshold used when OutputMode is Foam.
        /// </summary>
        public float FoamThreshold = 0.72f;

        /// <summary>
        /// Foam transition softness around FoamThreshold.
        /// </summary>
        public float FoamSoftness = 0.12f;

        /// <summary>
        /// Contrast applied around the 0.5 midpoint.
        /// </summary>
        public float Contrast = 1f;

        /// <summary>
        /// Additive brightness offset after contrast.
        /// </summary>
        public float Brightness;

        /// <summary>
        /// Whether to invert the generated grayscale output.
        /// </summary>
        public bool Invert;

        /// <inheritdoc />
        public override TextureLayerRole Role => TextureLayerRole.Source;

        /// <inheritdoc />
        public override bool SupportsRawPreview => true;

        /// <inheritdoc />
        public override void Process(BakeContext ctx)
        {
            LayerCompute.GetKernelOrThrow(LayerCompute.WaterWavesKernel, out var shader, out var kernel);
            LayerCompute.SetCommon(shader, kernel, ctx, Opacity, BlendMode, InputSwizzle, WriteMask);
            shader.SetVector(LayerCompute.WaterWaveSettingsId, new Vector4(
                Seed,
                WaveCount,
                Amplitude,
                Phase));
            shader.SetVector(LayerCompute.WaterWaveDirectionId, new Vector4(
                WindDirection * Mathf.Deg2Rad,
                DirectionSpread * Mathf.Deg2Rad,
                AmplitudeFalloff,
                Choppiness));
            shader.SetVector(LayerCompute.WaterWaveCyclesId, new Vector4(
                CycleRange.x,
                CycleRange.y,
                0f,
                0f));
            shader.SetVector(LayerCompute.WaterWaveOutputId, new Vector4(
                Contrast,
                Brightness,
                Invert ? 1f : 0f,
                (int)OutputMode));
            shader.SetVector(LayerCompute.WaterWaveFoamId, new Vector4(
                FoamThreshold,
                FoamSoftness,
                0f,
                0f));
            LayerCompute.Dispatch(shader, kernel, ctx);
        }
    }

    /// <summary>
    /// Output channel mode generated by WaterWavesLayer.
    /// </summary>
    public enum WaterWavesOutputMode
    {
        Height,
        Foam
    }
}
